### ISSUE TITLE
Don't automatically catch exceptions when enabling Sentry support

### ISSUE THREAD

**Issue by vincentbernat** [pyr/reporter#6]
Hey!

When enabling Sentry support, uncaught exceptions are automatically intercepted. This is surprising for a library to take over exceptions and an application may want to do things differently and invoke `capture!` manually. Let the user opt-out (or opt-in) on exception catching.

**Comment by pyr** [comment]
Hi.

`capture!` can always be invoked manually. A flag  to opt-out makes sense in case you already have one.

**Comment by llambiel** [comment]
+1 as we faced this issue in uri-dns

**Comment by pyr** [comment]
#9 provides an opt-out
